Limited Pillow version to prevent easyocr error
Pillow 10.0.0 removes ANTIALIAS which easyocr doesn't seem to have implemented the updated alternative of. This causes the following error during operation:
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'